### PR TITLE
optional cuda toolkit install

### PR DESCRIPTION
**Pull request by luismavs**
Addressing https://github.com/replicate/setup-cog/issues/9.

### CODE REVIEW

**Review by nateraw — APPROVED** [review]
LGTM :) thanks for adding this

**Comment by luismavs** [comment]
Hi, I added just a fix to a typo in documentation, ready to be merged ; )

**Comment by nateraw** [comment]
@zeke feel free to merge - I don't have write access. 

Also just a quick note, I'm still not 100% sure when (or if at all) you need the cuda toolkit install. Worth looking into

**Comment by zeke** [comment]
Sorry for the delay here folks! Thanks for the ping, @nateraw 

>  I don't have write access.

That's fixed now. :)

**Comment by zeke** [comment]
Created a GitHub Release for this: https://github.com/replicate/setup-cog/releases/tag/v1.0.3 🎉

**Pull request merged**
